### ISSUE TITLE
Setting it up on my server

### ISSUE THREAD

**Issue by ECHibiki** [bakape/captchouli#22]
Hey, 

I'm looking to integrate captchouli into my ViChan fork. I was impressed by it when I went on meguca and want to involve it in my efforts. 

How do I go about using it on my site?
Something like, you run main.go and it listens on a port for you to send post requests? 
Which files am I supposed to look at to understand setting it up on the client side?

**Comment by bakape** [comment]
Integration via a HTML/JSON API is planned. I'll get to writing and
documenting it some time this weekend.

**Comment by bakape** [comment]
I have added the functionality and documentation. If the docs seem lacking, feel free to reopen this issue.

**Comment by ECHibiki** [comment]
yeah, got it to work. I was https and apache ssl.conf proxypass so had to switch to ListenAndServeTLS to get it to work. Other than that no bugs or issues on my ubuntu18.04 apache server
