### ISSUE TITLE
Time limited captcha

### ISSUE THREAD

**Issue by Chiiruno** [bakape/captchouli#29]
Prevents googling the name.
Also having more than say 6 captchas go past the time limit would trigger ban, but that might be a meguca issue.
Anyway, two ways to fail, user fail and time limit fail, user fail is normal limit, time limit is normal times 2 perhaps.

**Comment by bakape** [comment]
Don't see this working, as there is no guarantee a user will try to solve a
captcha right after rendering one.

**Comment by Chiiruno** [comment]
Good point.
