### ISSUE TITLE
Obfuscate name of character or other tag

### ISSUE THREAD

**Issue by Chiiruno** [bakape/captchouli#30]
Use pre-captchouli captcha image obfuscation perhaps, use image of name instead of text.

**Comment by Chiiruno** [comment]
Basically, apply #6 to image of name of character, instead of copy-able text, will help prevent against basic OCR.

**Comment by bakape** [comment]
Care to demonstrate with an example?

**Comment by Chiiruno** [comment]
Like this, but with #6.
![image](https://user-images.githubusercontent.com/30435868/67145208-10cc4b00-f245-11e9-8cd1-127bc4128a1a.png)

**Comment by bakape** [comment]
That would not do much. Remember, the main purpose is to protect from bots.
Bots are very good at solving these.

**Comment by Chiiruno** [comment]
Good point. I can't think of any other route for this.
